using System.Text.Json.Serialization;

namespace Firebase.Authentication.Requests.IdentityPlatform;

/// <summary>
/// Model to send a accounts.resetPassword request
/// </summary>
public class ResetPasswordRequest
{
    /// <summary>
    /// Creates a new ResetPasswordRequest
    /// </summary>
    /// <param name="newPassword">The new password to be set for this account</param>
    /// <param name="oobCode">An out-of-band (OOB) code generated by accounts.sendOobCode request</param>
    /// <param name="oldPassword">The current password of the account to be modified. Specify this and email to change an account's password without using an out-of-band code</param>
    /// <param name="email">The email of the account to be modified</param>
    /// <param name="tenantId">The ID of the Identity Platform tenant the user is signing in to</param>
    public ResetPasswordRequest(
        string newPassword,
        string? oobCode = null,
        string? oldPassword = null,
        string? email = null,
        string? tenantId = null)
    {
        OobCode = oobCode;
        NewPassword = newPassword;
        OldPassword = oldPassword;
        Email = email;
        TenantId = tenantId;
    }

    /// <summary>
    /// The new password to be set for this account
    /// </summary>
    [JsonPropertyName("newPassword")]
    public string NewPassword { get; set; }

    /// <summary>
    /// An out-of-band (OOB) code generated by accounts.sendOobCode request
    /// </summary>
    [JsonPropertyName("oobCode")]
    public string? OobCode { get; set; }

    /// <summary>
    /// The current password of the account to be modified
    /// <br/>
    /// Specify this and email to change an account's password without using an out-of-band code
    /// </summary>
    [JsonPropertyName("oldPassword")]
    public string? OldPassword { get; set; }

    /// <summary>
    /// The email of the account to be modified
    /// </summary>
    [JsonPropertyName("email")]
    public string? Email { get; set; }

    /// <summary>
    /// The ID of the Identity Platform tenant the user is signing in to
    /// </summary>
    [JsonPropertyName("tenantId")]
    public string? TenantId { get; set; }
}